CREATE TABLE IF NOT EXISTS BASE_USER_PORTRAIT (
ROWKEY VARCHAR(100) NOT NULL PRIMARY KEY,
-- 姓名
BASICINFO.USER_NAME VARCHAR(100),
-- 性别	男、女、未知
BASICINFO.USER_SEX VARCHAR(100),
-- 年龄	18岁以下，18-25,25-35,35-45，45-55,55以上
BASICINFO.USER_AGE VARCHAR(100),
-- 职业	公务员、职员、教师、医生等
BASICINFO.USER_CAREER VARCHAR(100),
-- 学历	初中及以下、高中、本科、研究生及以上
BASICINFO.USER_DEGREE VARCHAR(100),
-- 婚姻状况	已婚、未婚、未知
BASICINFO.IS_MARRIED VARCHAR(100),
-- 是否有小孩	有、无、未知
BASICINFO.HAS_CHRILD VARCHAR(100),
-- 家庭人数
BASICINFO.FAMILY_SUM VARCHAR(100),
-- 所在省份
BASICINFO.LOCATION_PROVINCE VARCHAR(100),
-- 所在城市
BASICINFO.LOCATION_CITY VARCHAR(100),
-- 城市等级	一线、二线、三线、四线、五线
BASICINFO.CITY_TYPE VARCHAR(100),
-- 小区
BASICINFO.COMMUNITY VARCHAR(100),
-- 楼层
BASICINFO.FLOOR VARCHAR(100),
-- 房型	一室、两室、三室、四室、五室、五室以上
BASICINFO.HOUSE_TYPE VARCHAR(100),
-- 面积	50平以下，50-70平，70-90平，90-110平，110-140平，140-170平，170-200平，200平以上
BASICINFO.HOUSE_AREA VARCHAR(100),
-- 装修类型	毛培、简装、精装修
BASICINFO.FITMENT_TYPE VARCHAR(100),
-- 物业类型	住宅、别墅、公寓、商铺、写字楼
BASICINFO.ESTATE_TYPE VARCHAR(100),
-- 购买日期
BASICINFO.PURCHASE_DATE VARCHAR(100),
-- 付款方式	一次性付款、按揭借款付款
BASICINFO.PAYMENT_TYPE VARCHAR(100),
-- 总价
BASICINFO.TOTAL_PRICES VARCHAR(100),
-- 首付比例
BASICINFO.DOWN_PAYMENT_PERCENT VARCHAR(100),
-- 首付金额
BASICINFO.DOWN_PAYMENT_PRICES VARCHAR(100),
-- 贷款方式	公积金贷款、商业贷款、抵押贷款
BASICINFO.LOANS_TYPE VARCHAR(100),
-- 有否有车	有、无、未知
BASICINFO.HAS_CAR VARCHAR(100),
-- 是否有车位	有
BASICINFO.HAS_CARPORT VARCHAR(100)
);