#spring:
#  datasource:
#    url: jdbc:mysql://10.101.71.42:3306/read_data?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: hd123456
#    driver-class-name: com.mysql.jdbc.Driver
spring:
  datasource:
    url: jdbc:phoenix:10.101.71.41,10.101.71.42,10.101.71.43:2181/hbase
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver

mybatis:
  mapperLocations: classpath:config/mapper/*Mapper.xml